const datas = [
  {
    login: "prajjaldhar",
    id: 64453189,
    node_id: "MDQ6VXNlcjY0NDUzMTg5",
    avatar_url: "https://avatars.githubusercontent.com/u/64453189?v=4",
    gravatar_id: "",
    url: "https://api.github.com/users/prajjaldhar",
    html_url: "https://github.com/prajjaldhar",
    followers_url: "https://api.github.com/users/prajjaldhar/followers",
    following_url:
      "https://api.github.com/users/prajjaldhar/following{/other_user}",
    gists_url: "https://api.github.com/users/prajjaldhar/gists{/gist_id}",
    starred_url:
      "https://api.github.com/users/prajjaldhar/starred{/owner}{/repo}",
    subscriptions_url: "https://api.github.com/users/prajjaldhar/subscriptions",
    organizations_url: "https://api.github.com/users/prajjaldhar/orgs",
    repos_url: "https://api.github.com/users/prajjaldhar/repos",
    events_url: "https://api.github.com/users/prajjaldhar/events{/privacy}",
    received_events_url:
      "https://api.github.com/users/prajjaldhar/received_events",
    type: "User",
    site_admin: false,
    name: "Prj_Rocks",
    company: null,
    blog: "https://www.linkedin.com/in/prajjal-dhar-24x7/",
    location: null,
    email: null,
    hireable: true,
    bio: "MERN STACK DEVELOPER | | SOFTWARE DEVELOPER | | WEB DEVELOPER | | MACHINE LEARNING ENTHUSIAST | | REACT_JS NODEJ_S DEVELOPER | | DATA SCIENTIST",
    twitter_username: null,
    public_repos: 45,
    public_gists: 0,
    followers: 19,
    following: 3,
    created_at: "2020-04-28T03:27:46Z",
    updated_at: "2024-01-11T14:09:38Z",
  },
];
export default datas;
